apiVersion: v1
kind: ConfigMap
metadata:
  name: umbrella-selfdescription-application-config
  namespace: umbrella
data:
  application.yml: |
    server:
      port: 8080
      error:
        include-message: always
    
    keycloak:
      resource:
        clientid: "sa-cl8-cx-1"
    
    spring:
      jackson:
        default-property-inclusion: non_null
      profiles:
        active: tagus-ctx
      security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: "http://centralidp.tx.test/auth/realms/CX-Central/protocol/openid-connect/certs"
    
    springdoc:
      api-docs:
        enabled: true
      swagger-ui:
        url: /SDFactoryApi-Tagus.yml
    
    app:
      build:
        version: "2.1.23"
      verifiableCredentials:
        durationDays: 90
        schema2210Url: "https://w3id.org/gaia-x/trust-framework/v22.10/schemas/SD-document.jsonld"
        catena-x-ns: "https://catena-x.net/selfdescription#"
      usersDetails:
        clearingHouse:
          uri: ""
          serverUrl: ""
          realm: ""
          clientId: ""
          clientSecret: ""
        custodianWallet:
          uri: ""
          authServerUrl: ""
          realm: ""
          clientId: ""
          clientSecret: ""
      security:
        createRole: add_self_descriptions 