# argocd/applications/umbrella-application-multi-source.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umbrella-multi-source
  namespace: argocd
  labels:
    app.kubernetes.io/name: umbrella
    app.kubernetes.io/part-of: tractus-x
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  
  # Use multiple sources to handle local charts
  sources:
    # Main umbrella chart
    - repoURL: https://github.com/aminshuvo/tractus-x-umbrella-umbrella
      targetRevision: main
      path: charts/umbrella
      helm:
        valueFiles:
          - values-dev.yaml
        # Override dependencies to use remote repositories
        parameters:
          - name: discoveryfinder.repository
            value: https://eclipse-tractusx.github.io/charts/dev
          - name: bpndiscovery.repository
            value: https://eclipse-tractusx.github.io/charts/dev
          - name: semantic-hub.repository
            value: https://eclipse-tractusx.github.io/charts/dev
  
  destination:
    server: https://kubernetes.default.svc
    namespace: umbrella
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
      - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
  
  # Ignore differences in resource requirements and replicas for dev environment
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
        - /spec/template/spec/containers/0/resources/requests
        - /spec/template/spec/containers/0/resources/limits
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec/resources/requests/storage 